spring:
  application:
    name: LAA Information and Advice Datastore

  # example database
  datasource:
    url: jdbc:postgresql://localhost:5432/laa_info_advice_datastore
    driver-class-name: org.postgresql.Driver
    username: laa_user
    password: laa_password
  h2:
    console:
      enabled: true

  #do not auto create db schema, use .sql scripts
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

# used by actuator info endpoint
info:
  app:
    name: LAA Information and Advice Datastore
    description: Datastore for information and advice
    version: 1.0.0

management:
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health
