openapi: "3.0.0"
info:
  version: 1.0.0
  title: Info and Advice Datastore API
paths:
  /api/v0/applications:
    get:
      tags:
        - application
      summary: Get applications
      operationId: getApplications
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 25
        - name: officeId
          in: query
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationResponses"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

  /api/v0/applications/{id}:
    get:
      tags:
        - application
      summary: Get application by ID
      operationId: getApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationResponse"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
  /api/v0/applications/{id}:update-means-data:
    put:
      tags:
        - application
      operationId: updateMeansData
      summary: Update means data for an application
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: If-Match
          in: header
          required: true
          description: ETag version of the application to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '404':
          description: Not found
        '409':
          description: Conflict - ETag version mismatch
        '500':
          description: Internal server error
  /api/v0/applications:start-case:
    post:
      tags:
        - application
      operationId: startCase
      summary: Start an application/case for a client
      requestBody:
        required: true
        description: Information required to start an application/case
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/StartCaseCommand'
      responses:
        '201' : { description: Created }
        '400' : { description: Bad request }
        '500' : { description: Internal server error }
  /api/v0/applications/{id}:update-evidence:
    put:
      tags:
        - application
      summary: Update evidence for an application
      operationId: updateEvidence
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: If-Match
          in: header
          required: true
          description: ETag version of the application to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        description: Confirmation of the evidence statement for the application.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEvidenceCommand'
      responses:
        '204':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Application not found
        '409':
          description: Conflict - ETag version mismatch
        '500':
          description: Internal server error

  /api/v0/applications/{id}/declaration:
    put:
      tags:
        - application
      summary: Update declaration for an application
      operationId: updateDeclaration
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: If-Match
          in: header
          required: true
          description: ETag version of the application to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        description: Confirmation of the declaration statement for the application.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeclarationCommand'
      responses:
        '204':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Application not found
        '409':
          description: Conflict - ETag version mismatch
        '500':
          description: Internal server error

components:
  schemas:
    ClientDetails:
      $ref: "./open-api-applications/client-details-components.yml#/components/schemas/ClientDetails"

    Address:
      $ref: "./open-api-applications/client-details-components.yml#/components/schemas/Address"
    
    ApplicationResponse:
      type: object
      required:
        - id
        - individualLegalAidNumber
        - client
        - providerFirmId
        - providerOfficeId
        - createdAt
        - createdBy
        - modifiedAt
        - modifiedBy
      properties:
        id:
          type: string
          format: uuid
          example: 
        individualLegalAidNumber:
          type: string
          format: uuid
          example:
          description:
        client:
          $ref: "#/components/schemas/ClientDetails"
        providerFirmId:
          type: string 
          format: uuid
          example:
          description:
        providerOfficeId:
          type: string 
          format: uuid
          example: 
          description:
        applicationState:
          $ref: "#/components/schemas/ApplicationState"
        declaration:
          $ref: "#/components/schemas/DeclarationResponse"
        evidence:
          type: object
        reasonForReapplication:
          type: string
        meansAssessmentRequired:
          type: boolean
        typeOfNonMeans:
          type: boolean
        ecfFlag:
          type: boolean
        contribution:
          type: string
        referenceNumber:
          type: string
        applicationType:
          type: string
        determinationId:
          type: string
          format: uuid
        eligibilityResult:
          $ref: "#/components/schemas/EligibilityResultResponse"
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string
        version:
          type: integer
          format: int64
          description: ETag version for optimistic concurrency control

    ApplicationSummary:
      type: object
      description: Slim representation of an application for use in list views
      required:
        - id
        - referenceNumber
        - modifiedAt
      properties:
        id:
          type: string
          format: uuid
        clientFirstName:
          type: string
        clientLastName:
          type: string
        referenceNumber:
          type: string
        modifiedAt:
          type: string
          format: date-time

    ApplicationResponses:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/ApplicationSummary"
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer

    DeclarationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        clientDeclarationStatus:
          $ref: "#/components/schemas/ClientDeclarationStatus"
        declarationConfirmation:
          type: boolean
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string

    ClientDeclarationStatus:
      type: string
      enum:
        - DRAFT

    ApplicationState:
      type: string
      enum:
        - DRAFT

    StartCaseCommand:
      type: object
      required:
        - client
        - applicationType
        - providerOfficeId
      properties:
        client: 
          $ref: "./open-api-applications/client-details-components.yml#/components/schemas/CreateClientCommand"
        applicationType:
          type: string
          enum:
            - RCW
            - CLA
        providerOfficeId:
          type: string
          format: uuid
            

    DeclarationCommand:
      type: object
      required:
        - declarationConfirmation
      properties:
        declarationConfirmation:
          type: boolean
    UpdateEvidenceCommand:
      type: object
      additionalProperties: true
      minProperties: 1

    EligibilityResultResponse:
      type: object
      properties:
        eligibilityResultId:
          type: string
          format: uuid
        applicationId:
          type: string
          format: uuid
        eligibilityResult:
          type: object
        createdAt:
          type: string
          format: date-time
