openapi: "3.0.0"
info:
  version: 1.0.0
  title: Info and Advice Datastore API
paths:
  /api/v0/applications:
    get:
      tags:
        - application
      summary: Get applications
      operationId: getApplications
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 25
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationResponses"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error
  /api/v0/individuals:
    get:
      tags:
        - individuals
      summary: Get individuals
      operationId: getIndividuals
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Individuals"
        '401': { description: 'Unauthorized' }
        '403': { description: 'Forbidden' }
        '500': { description: 'Internal server error' }
  /api/v0/individuals/{id}:
    get:
      tags:
        - individuals
      summary: Get individual
      operationId: getIndividual
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Individual"
        '401' : { description: 'Unauthorized' }
        '403' : { description: 'Forbidden' }
        '404' : { description: 'Not found' }
        '500' : { description: 'Internal server error' }
  /api/v0/applications:start-case:
    post:
      tags:
        - application
      operationId: startCase
      summary: Start an application/case for a client
      requestBody:
        required: true
        description: Information required to start an application/case
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/StartCaseCommand'
      responses:
        '201' : { description: Created }
        '400' : { description: Bad request }
        '500' : { description: Internal server error }

components:
  schemas:
    Individual:
      properties:
        individualLegalAidNumber:
          type: string
          format: uuid
        fullName:
          type: string
        dateOfBirth:
          type: string
          format: date
        niNumber:
          type: string
          example: QQ123456B
          minLength: 9
          maxLength: 9
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type: string
          format: date-time
    Individuals:
      type: array
      items:
        $ref: "#/components/schemas/Individual"

    Address:
      properties:
        addressLine1:
          type: string
        addressLine2:
          type: string
        townOrCity:
          type: string
        postCode:
          type: string
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type: string
          format: date-time
    
    ApplicationResponse:
      type: object
      required:
        - referenceNumber
        - individualLegalAidNumber
        - providerFirmId
        - providerOfficeId
        - createdAt
        - createdBy
        - modifiedAt
        - modifiedBy
      properties:
        referenceNumber:
          type: string
          format: uuid
          example: 
        individualLegalAidNumber:
          type: string
          format: uuid
          example:
          description:
        providerFirmId:
          type: string 
          format: uuid
          example:
          description:
        providerOfficeId:
          type: string 
          format: uuid
          example: 
          description:
        eligibilityResult:
          type: string
          format: uuid
          example:
          description:
        clientCaseDetailsStatus:
          $ref: "#/components/schemas/ClientCaseDetailsStatus"
        meansAssessmentStatus:
          type: string
          format: uuid
        evidenceStatus:
          type: string
          format: uuid
        clientDeclarationStatus:
          type: string
          format: uuid
        overallApplicationStatus:
          $ref: "#/components/schemas/OverallApplicationStatus"
        declaration:
          $ref: "#/components/schemas/DeclarationResponse"
        evidence:
          $ref: "#/components/schemas/EvidenceResponse"
        uniqueFileNumber:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string

    ApplicationResponses:
      type: array
      items:
        $ref: "#/components/schemas/ApplicationResponse"

    DeclarationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        clientDeclarationStatus:
          $ref: "#/components/schemas/ClientDeclarationStatus"
        declarationStatement:
          type: boolean
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string

    EvidenceResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        evidenceStatus:
          $ref: "#/components/schemas/EvidenceStatus"
        payeIncomeEvidence:
          type: boolean
        otherIncomeEvidence:
          type: boolean
        housingCostsEvidence:
          type: boolean
        capitalEvidence:
          type: boolean
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string

    ClientCaseDetailsStatus:
      type: string
      enum:
        - DRAFT

    ClientDeclarationStatus:
      type: string
      enum:
        - DRAFT
    EvidenceStatus:
      type: string
      enum:
        - DRAFT
    OverallApplicationStatus:
      type: string
      enum:
        - DRAFT

    StartCaseCommand:
      type: object
      required:
        - client
        - caseDetails
      properties:
        client: 
          $ref: '#/components/schemas/CreateClientCommand'
            
    CreateClientCommand:
      type: object
      required:
        - fullName
        - dateOfBirth
        - placeOfBirth
      properties:
        fullName:
          type: string
        dateOfBirth:
           type: string
           format: date
        placeOfBirth:
          type: string
        nationalInsuranceNumber:
          type: string
          pattern: '/[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}/'
          example: AC123456D
        createAddressCommand:
          $ref: '#/components/schemas/CreateAddressCommand'

    CreateAddressCommand:
      type: object
      properties:
        line1:
          type: string
          example: 10 Downing Street
        line2:
          type: string
        city:
          type: string
          example: London
        postCode:
          type: string 
          example: SW1A 2AA

        country:
          type: string
          example: England
          
