openapi: "3.0.0"
info:
  version: 1.0.0
  title: Info and Advice Datastore API
paths:
  /api/v0/applications:
    $ref: './open-api-applications/paths/applications.yml'
  /api/v0/applications/{id}:
    $ref: './open-api-applications/paths/application-by-id.yml'
  /api/v0/applications/{id}:update-means-data:
    $ref: './open-api-applications/paths/application-update-means-data.yml'
  /api/v0/applications:start-application:
    $ref: './open-api-applications/paths/application-start.yml'
  /api/v0/applications/{id}:update-evidence:
    $ref: './open-api-applications/paths/application-update-evidence.yml'
  /api/v0/applications/{id}:update-scoping-data:
    $ref: './open-api-applications/paths/application-update-scoping-data.yml'
  /api/v0/applications/{id}:update-declaration-data:
    $ref: './open-api-applications/paths/application-update-declaration-data.yml'
  /api/v0/applications/{id}:update-application:
    $ref: './open-api-applications/paths/application-update-application.yml'

components:
  parameters:
    XAuthorizationHeader:
      $ref: './open-api-applications/components/parameters.yml#/components/parameters/XAuthorizationHeader'

  schemas:
    ClientDetails:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/ClientDetails'
    Address:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/Address'
    ApplicationResponse:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/ApplicationResponse'
    ApplicationSummary:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/ApplicationSummary'
    ApplicationResponses:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/ApplicationResponses'
    DeclarationResponse:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/DeclarationResponse'
    ClientDeclarationStatus:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/ClientDeclarationStatus'
    ApplicationState:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/ApplicationState'
    StartApplicationCommand:
      $ref: './open-api-applications/components/request-schemas.yml#/components/schemas/StartApplicationCommand'
    DeclarationCommand:
      $ref: './open-api-applications/components/request-schemas.yml#/components/schemas/DeclarationCommand'
    UpdateEvidenceCommand:
      $ref: './open-api-applications/components/request-schemas.yml#/components/schemas/UpdateEvidenceCommand'
    EvidenceResponse:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/EvidenceResponse'
    UpdateMeansDataCommand:
      $ref: './open-api-applications/components/request-schemas.yml#/components/schemas/UpdateMeansDataCommand'
    UpdateScopingDataCommand:
      $ref: './open-api-applications/components/request-schemas.yml#/components/schemas/UpdateScopingDataCommand'
    EligibilityResult:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/EligibilityResult'
    ApiError:
      $ref: './open-api-applications/components/response-schemas.yml#/components/schemas/ApiError'
