components:
  parameters:
    XAuthorizationHeader:
      name: X-Authorization
      in: header
      required: true
      schema:
        type: string
      description: Bearer prefix required. JWT representing the user, FIRM_CODE claim required.