{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "laa-info-and-advice-datastore.fullname" . }}
  labels:
    {{- include "laa-info-and-advice-datastore.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "laa-info-and-advice-datastore.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
{{- end }}
