get:
  tags:
    - application
  summary: Get application by ID
  operationId: getApplication
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    - $ref: '../components/parameters.yml#/components/parameters/XAuthorizationHeader'
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApplicationResponse'
    '401':
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApiError'
    '403':
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApiError'
    '404':
      description: Not found
      content:
        application/problem+json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApiError'
    '500':
      description: Internal server error
      content:
        application/problem+json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApiError'