post:
  tags:
    - application
  operationId: startApplication
  summary: Start an application for a client
  parameters:
    - $ref: '../components/parameters.yml#/components/parameters/XAuthorizationHeader'
  requestBody:
    required: true
    description: Information required to start an application
    content:
      application/json:
        schema:
          $ref: '../components/request-schemas.yml#/components/schemas/StartApplicationCommand'
  responses:
    '201':
      description: Application created successfully
      content:
        application/json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApplicationResponse'
    '400':
      description: Bad request
      content:
        application/problem+json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApiError'
    '401':
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApiError'
    '403':
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApiError'
    '500':
      description: Internal server error
      content:
        application/problem+json:
          schema:
            $ref: '../components/response-schemas.yml#/components/schemas/ApiError'